export const easyQuestions = [
  // 地理・世界 (1-8)
  {
    question: "世界で一番大きい大陸はどれですか？",
    answers: [
      "アフリカ大陸",
      "北アメリカ大陸",
      "ユーラシア大陸",
      "南アメリカ大陸",
    ],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question:
      "エジプトにある有名な建造物「ピラミッド」がある場所はどこですか？",
    answers: ["ギザ", "カイロ", "ルクソール", "アレクサンドリア"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "アメリカ合衆国の首都はどこですか？",
    answers: ["ニューヨーク", "ロサンゼルス", "シカゴ", "ワシントンD.C."],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "世界で一番面積が大きい国はどこですか？",
    answers: ["ロシア", "カナダ", "中国", "アメリカ"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "オーストラリアの首都はどこですか？",
    answers: ["シドニー", "メルボルン", "キャンベラ", "ブリスベン"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "中国の首都はどこですか？",
    answers: ["上海", "広州", "香港", "北京"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "イタリアの首都はどこですか？",
    answers: ["ミラノ", "ナポリ", "ベネチア", "ローマ"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "世界で一番長い川はどれですか？",
    answers: ["ナイル川", "アマゾン川", "ミシシッピ川", "長江"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  // 日本の地理 (9-18)
  {
    question: "日本で一番高い山は何ですか？",
    answers: ["北岳", "奥穂高岳", "槍ヶ岳", "富士山"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "日本で一番大きい湖はどれですか？",
    answers: ["琵琶湖", "霞ヶ浦", "サロマ湖", "猪苗代湖"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "北海道の県庁所在地はどこですか？",
    answers: ["函館市", "旭川市", "札幌市", "釧路市"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "日本で一番面積が大きい都道府県はどこですか？",
    answers: ["北海道", "岩手県", "長野県", "新潟県"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "沖縄県の県庁所在地はどこですか？",
    answers: ["名護市", "沖縄市", "那覇市", "宜野湾市"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "日本の都道府県はいくつありますか？",
    answers: ["43", "45", "47", "50"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "日本で一番小さい都道府県はどこですか？",
    answers: ["大阪府", "東京都", "沖縄県", "香川県"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「たこ焼き」が名物の都道府県はどこですか？",
    answers: ["大阪府", "東京都", "京都府", "兵庫県"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "日本の四国にある県は何県ありますか？",
    answers: ["3県", "4県", "5県", "6県"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "東京タワーがある都市はどこですか？",
    answers: ["横浜市", "さいたま市", "千葉市", "東京都港区"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  // 科学・自然 (19-28)
  {
    question: "地球は太陽の周りを何日かけて一周しますか？",
    answers: ["約365日", "約180日", "約30日", "約730日"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "月は地球の周りを約何日で一周しますか？",
    answers: ["約7日", "約27日", "約14日", "約60日"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "氷は何度で溶け始めますか？（摂氏）",
    answers: ["-10℃", "0℃", "10℃", "100℃"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "水が沸騰するのは何度ですか？（摂氏・1気圧）",
    answers: ["50℃", "80℃", "90℃", "100℃"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "太陽系の惑星で、地球のすぐ外側を回っている惑星は何ですか？",
    answers: ["火星", "金星", "木星", "土星"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "空気中に最も多く含まれている気体は何ですか？",
    answers: ["酸素", "窒素", "二酸化炭素", "水素"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "磁石のN極が指す方角はどれですか？",
    answers: ["南", "東", "西", "北"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "植物が光合成で作り出すものは何ですか？",
    answers: ["二酸化炭素", "窒素", "酸素と栄養分", "水素"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "雷が光ってから音が遅れて聞こえるのはなぜですか？",
    answers: [
      "光のほうが速いから",
      "音のほうが速いから",
      "雷が2回鳴るから",
      "気のせい",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "太陽系の惑星で「輪」があることで有名な惑星はどれですか？",
    answers: ["火星", "土星", "木星", "天王星"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 生物 (29-38)
  {
    question: "パンダの主な食べ物は何ですか？",
    answers: ["果物", "魚", "昆虫", "笹（竹）"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "イルカは魚類ですか、哺乳類ですか？",
    answers: ["魚類", "哺乳類", "爬虫類", "両生類"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "昆虫の足は全部で何本ですか？",
    answers: ["4本", "6本", "8本", "10本"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "カエルの子どもは何と呼ばれますか？",
    answers: ["メダカ", "ヤゴ", "おたまじゃくし", "イモリ"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "クモの足は全部で何本ですか？",
    answers: ["6本", "10本", "12本", "8本"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "世界で一番大きい動物は何ですか？",
    answers: ["アフリカゾウ", "シロナガスクジラ", "キリン", "ジンベエザメ"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "サケは川と海のどちらで生まれますか？",
    answers: ["海", "湖", "池", "川"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "桜の花びらは通常何枚ですか？（ソメイヨシノ）",
    answers: ["3枚", "5枚", "7枚", "10枚"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "ペンギンは空を飛べますか？",
    answers: ["飛べる", "少しだけ飛べる", "飛べない", "子どものときだけ飛べる"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "キリンの首の骨の数は人間と比べてどうですか？",
    answers: ["人間より多い", "人間と同じ7個", "人間より少ない", "骨がない"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 日本史 (39-46)
  {
    question: "鎌倉幕府を開いた人物は誰ですか？",
    answers: ["源頼朝", "平清盛", "足利尊氏", "徳川家康"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "江戸幕府を開いた人物は誰ですか？",
    answers: ["豊臣秀吉", "織田信長", "武田信玄", "徳川家康"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "本能寺の変で討たれた武将は誰ですか？",
    answers: ["豊臣秀吉", "徳川家康", "織田信長", "武田信玄"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "「天下統一」を果たしたとされる戦国武将は誰ですか？",
    answers: ["織田信長", "徳川家康", "武田信玄", "豊臣秀吉"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "聖徳太子が建てたとされるお寺はどれですか？",
    answers: ["東大寺", "金閣寺", "法隆寺", "清水寺"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "明治維新が起きたのは何年ですか？",
    answers: ["1868年", "1853年", "1889年", "1912年"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "日本最初のオリンピック出場は何年ですか？",
    answers: ["1896年", "1936年", "1912年", "1964年"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "奈良の大仏がある寺はどこですか？",
    answers: ["法隆寺", "東大寺", "薬師寺", "興福寺"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 日本文化 (47-53)
  {
    question: "お正月に食べる伝統的な料理を何と言いますか？",
    answers: ["お雑煮", "すき焼き", "天ぷら", "おせち料理"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "七五三は何歳の子どものお祝いですか？",
    answers: [
      "1歳・3歳・5歳",
      "3歳・5歳・7歳",
      "5歳・7歳・9歳",
      "2歳・4歳・6歳",
    ],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "ひな祭りは何月何日ですか？",
    answers: ["2月3日", "4月4日", "5月5日", "3月3日"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "こどもの日は何月何日ですか？",
    answers: ["3月3日", "4月4日", "5月5日", "6月6日"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "日本の国技は何ですか？",
    answers: ["相撲", "柔道", "剣道", "空手"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "茶道で使う粉末状のお茶を何と言いますか？",
    answers: ["煎茶", "ほうじ茶", "抹茶", "番茶"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "日本の国花とされることが多い花はどれですか？",
    answers: ["ひまわり", "桜", "チューリップ", "バラ"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 言葉・漢字 (54-61)
  {
    question: "「山」という漢字の読み方で正しいのはどれですか？",
    answers: ["かわ", "うみ", "もり", "やま"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「犬」の反対の意味の動物として、よく対比されるのはどれですか？",
    answers: ["猫", "鳥", "馬", "牛"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「雨」の読み方はどれですか？",
    answers: ["あめ", "かぜ", "ゆき", "くも"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「上」の反対の意味の漢字はどれですか？",
    answers: ["右", "下", "左", "中"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "「赤」「青」「黄」のうち、信号機にないのはどれですか？",
    answers: ["赤", "青", "黄", "全部ある"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「月」という漢字の読み方で正しいのはどれですか？",
    answers: ["つき", "ほし", "ひ", "そら"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "五十音の最初の文字は何ですか？",
    answers: ["い", "う", "あ", "え"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "アルファベットは全部で何文字ですか？",
    answers: ["24文字", "26文字", "28文字", "30文字"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // ことわざ (62-68)
  {
    question: "「猿も木から○○」の○○に入る言葉は？",
    answers: ["飛ぶ", "登る", "降りる", "落ちる"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「犬も歩けば○○に当たる」の○○に入る言葉は？",
    answers: ["棒", "石", "壁", "人"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「花より○○」の○○に入る言葉は？",
    answers: ["月", "団子", "酒", "風"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "「三日○○」の○○に入る言葉は？",
    answers: ["天下", "大名", "坊主", "小僧"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "「早起きは三文の○○」の○○に入る言葉は？",
    answers: ["損", "得", "徳", "福"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "「石の上にも○○」の○○に入る言葉は？",
    answers: ["三年", "一年", "二年", "五年"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「塵も積もれば○○となる」の○○に入る言葉は？",
    answers: ["海", "川", "丘", "山"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  // スポーツ (69-76)
  {
    question: "サッカーは1チーム何人でプレーしますか？",
    answers: ["9人", "10人", "11人", "12人"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "野球は1チーム何人でプレーしますか？",
    answers: ["8人", "9人", "10人", "11人"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "バスケットボールは1チーム何人でプレーしますか？",
    answers: ["5人", "4人", "6人", "7人"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "オリンピックは何年ごとに開催されますか？",
    answers: ["2年ごと", "3年ごと", "4年ごと", "5年ごと"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "マラソンの距離は約何キロメートルですか？",
    answers: ["約32km", "約52km", "約62km", "約42km"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "テニスで得点が0のことを何と言いますか？",
    answers: ["ラブ", "ゼロ", "ナッシング", "ブランク"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "大相撲の最高位は何ですか？",
    answers: ["大関", "横綱", "関脇", "小結"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "ボウリングのピンは全部で何本ですか？",
    answers: ["8本", "12本", "10本", "15本"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  // 食・生活 (77-84)
  {
    question: "お米を炊く前に行う作業は何ですか？",
    answers: ["焼く", "揚げる", "蒸す", "研ぐ（とぐ）"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "味噌汁の主な原料は何ですか？",
    answers: ["醤油", "味噌", "塩", "酢"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "お寿司に使われる酢飯の「酢」は何からできていますか？",
    answers: ["小麦", "米", "大豆", "とうもろこし"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "豆腐の原料は何ですか？",
    answers: ["小麦", "米", "大豆", "そば"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "カレーライスの「ライス」とは何のことですか？",
    answers: ["ご飯", "パン", "麺", "芋"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "日本で一番多く生産されている果物はどれですか？",
    answers: ["りんご", "ぶどう", "もも", "みかん"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「醤油」の原料に含まれるのはどれですか？",
    answers: ["牛乳", "卵", "大豆", "砂糖"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "納豆は何を発酵させた食べ物ですか？",
    answers: ["大豆", "米", "小麦", "とうもろこし"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  // 算数・数学の基礎 (85-93)
  {
    question: "三角形の内角の和は何度ですか？",
    answers: ["90度", "180度", "270度", "360度"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "四角形の内角の和は何度ですか？",
    answers: ["180度", "270度", "360度", "450度"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "1キログラムは何グラムですか？",
    answers: ["10グラム", "100グラム", "10000グラム", "1000グラム"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "1メートルは何センチメートルですか？",
    answers: ["100cm", "10cm", "1000cm", "10000cm"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "1時間は何分ですか？",
    answers: ["30分", "60分", "45分", "100分"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "円の形をした図形の周りの長さを何と言いますか？",
    answers: ["面積", "直径", "半径", "円周"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "2の3乗はいくつですか？",
    answers: ["6", "8", "9", "12"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question: "1キロメートルは何メートルですか？",
    answers: ["10m", "100m", "1000m", "10000m"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "偶数でないのはどれですか？",
    answers: ["2", "7", "4", "10"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 音楽・エンタメ基礎 (94-100)
  {
    question: "ドレミファソラシドの「ド」は英語で何と言いますか？",
    answers: ["A", "B", "C", "D"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "ピアノの鍵盤で白い鍵と黒い鍵、多いのはどちらですか？",
    answers: ["白い鍵", "黒い鍵", "同じ数", "ピアノによる"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「桃太郎」でお供にならなかった動物はどれですか？",
    answers: ["猫", "犬", "猿", "キジ"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "「浦島太郎」が助けた動物は何ですか？",
    answers: ["鶴", "魚", "ウサギ", "亀"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question: "「かぐや姫」はどこから生まれましたか？",
    answers: ["竹", "桃", "栗", "柿"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question: "音楽の「四分音符」は「八分音符」何個分の長さですか？",
    answers: ["1個分", "3個分", "2個分", "4個分"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question: "ギターの弦は一般的に何本ですか？",
    answers: ["4本", "6本", "5本", "8本"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
];
