export const easyQuestions = [
  // 地理・世界 (1-8)
  {
    question_ja: "世界で一番大きい大陸はどれですか？",
    question_en: "Which is the largest continent in the world?",
    answers_ja: [
      "アフリカ大陸",
      "北アメリカ大陸",
      "ユーラシア大陸",
      "南アメリカ大陸",
    ],
    answers_en: ["Africa", "North America", "Eurasia", "South America"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja:
      "エジプトにある有名な建造物「ピラミッド」がある場所はどこですか？",
    question_en: "Where are the famous Pyramids located in Egypt?",
    answers_ja: ["ギザ", "カイロ", "ルクソール", "アレクサンドリア"],
    answers_en: ["Giza", "Cairo", "Luxor", "Alexandria"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "アメリカ合衆国の首都はどこですか？",
    question_en: "What is the capital of the United States?",
    answers_ja: ["ニューヨーク", "ロサンゼルス", "シカゴ", "ワシントンD.C."],
    answers_en: ["New York", "Los Angeles", "Chicago", "Washington D.C."],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "世界で一番面積が大きい国はどこですか？",
    question_en: "Which country has the largest area in the world?",
    answers_ja: ["ロシア", "カナダ", "中国", "アメリカ"],
    answers_en: ["Russia", "Canada", "China", "United States"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "オーストラリアの首都はどこですか？",
    question_en: "What is the capital of Australia?",
    answers_ja: ["シドニー", "メルボルン", "キャンベラ", "ブリスベン"],
    answers_en: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "中国の首都はどこですか？",
    question_en: "What is the capital of China?",
    answers_ja: ["上海", "広州", "香港", "北京"],
    answers_en: ["Shanghai", "Guangzhou", "Hong Kong", "Beijing"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "イタリアの首都はどこですか？",
    question_en: "What is the capital of Italy?",
    answers_ja: ["ミラノ", "ナポリ", "ベネチア", "ローマ"],
    answers_en: ["Milan", "Naples", "Venice", "Rome"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "世界で一番長い川はどれですか？",
    question_en: "Which is the longest river in the world?",
    answers_ja: ["ナイル川", "アマゾン川", "ミシシッピ川", "長江"],
    answers_en: [
      "Nile River",
      "Amazon River",
      "Mississippi River",
      "Yangtze River",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  // 日本の地理 (9-18)
  {
    question_ja: "日本で一番高い山は何ですか？",
    question_en: "What is the tallest mountain in Japan?",
    answers_ja: ["北岳", "奥穂高岳", "槍ヶ岳", "富士山"],
    answers_en: ["Mt. Kita", "Mt. Okuhotaka", "Mt. Yari", "Mt. Fuji"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本で一番大きい湖はどれですか？",
    question_en: "Which is the largest lake in Japan?",
    answers_ja: ["琵琶湖", "霞ヶ浦", "サロマ湖", "猪苗代湖"],
    answers_en: [
      "Lake Biwa",
      "Lake Kasumigaura",
      "Lake Saroma",
      "Lake Inawashiro",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "北海道の県庁所在地はどこですか？",
    question_en: "What is the capital city of Hokkaido?",
    answers_ja: ["函館市", "旭川市", "札幌市", "釧路市"],
    answers_en: ["Hakodate", "Asahikawa", "Sapporo", "Kushiro"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本で一番面積が大きい都道府県はどこですか？",
    question_en: "Which prefecture has the largest area in Japan?",
    answers_ja: ["北海道", "岩手県", "長野県", "新潟県"],
    answers_en: [
      "Hokkaido",
      "Iwate Prefecture",
      "Nagano Prefecture",
      "Niigata Prefecture",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "沖縄県の県庁所在地はどこですか？",
    question_en: "What is the capital city of Okinawa Prefecture?",
    answers_ja: ["名護市", "沖縄市", "那覇市", "宜野湾市"],
    answers_en: ["Nago", "Okinawa City", "Naha", "Ginowan"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本の都道府県はいくつありますか？",
    question_en: "How many prefectures are there in Japan?",
    answers_ja: ["43", "45", "47", "50"],
    answers_en: ["43", "45", "47", "50"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本で一番小さい都道府県はどこですか？",
    question_en: "Which is the smallest prefecture in Japan by area?",
    answers_ja: ["大阪府", "東京都", "沖縄県", "香川県"],
    answers_en: [
      "Osaka Prefecture",
      "Tokyo",
      "Okinawa Prefecture",
      "Kagawa Prefecture",
    ],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「たこ焼き」が名物の都道府県はどこですか？",
    question_en: "Which prefecture is famous for 'takoyaki' (octopus balls)?",
    answers_ja: ["大阪府", "東京都", "京都府", "兵庫県"],
    answers_en: [
      "Osaka Prefecture",
      "Tokyo",
      "Kyoto Prefecture",
      "Hyogo Prefecture",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本の四国にある県は何県ありますか？",
    question_en: "How many prefectures are on the island of Shikoku in Japan?",
    answers_ja: ["3県", "4県", "5県", "6県"],
    answers_en: [
      "3 prefectures",
      "4 prefectures",
      "5 prefectures",
      "6 prefectures",
    ],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "東京タワーがある都市はどこですか？",
    question_en: "In which area is Tokyo Tower located?",
    answers_ja: ["横浜市", "さいたま市", "千葉市", "東京都港区"],
    answers_en: ["Yokohama", "Saitama City", "Chiba City", "Minato, Tokyo"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  // 科学・自然 (19-28)
  {
    question_ja: "地球は太陽の周りを何日かけて一周しますか？",
    question_en: "How many days does it take for the Earth to orbit the Sun?",
    answers_ja: ["約365日", "約180日", "約30日", "約730日"],
    answers_en: [
      "About 365 days",
      "About 180 days",
      "About 30 days",
      "About 730 days",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "月は地球の周りを約何日で一周しますか？",
    question_en:
      "Approximately how many days does it take for the Moon to orbit the Earth?",
    answers_ja: ["約7日", "約27日", "約14日", "約60日"],
    answers_en: [
      "About 7 days",
      "About 27 days",
      "About 14 days",
      "About 60 days",
    ],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "氷は何度で溶け始めますか？（摂氏）",
    question_en: "At what temperature does ice begin to melt (in Celsius)?",
    answers_ja: ["-10℃", "0℃", "10℃", "100℃"],
    answers_en: ["-10°C", "0°C", "10°C", "100°C"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "水が沸騰するのは何度ですか？（摂氏・1気圧）",
    question_en: "At what temperature does water boil (in Celsius, at 1 atm)?",
    answers_ja: ["50℃", "80℃", "90℃", "100℃"],
    answers_en: ["50°C", "80°C", "90°C", "100°C"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "太陽系の惑星で、地球のすぐ外側を回っている惑星は何ですか？",
    question_en:
      "Which planet orbits just outside of Earth in the solar system?",
    answers_ja: ["火星", "金星", "木星", "土星"],
    answers_en: ["Mars", "Venus", "Jupiter", "Saturn"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "空気中に最も多く含まれている気体は何ですか？",
    question_en: "What is the most abundant gas in the atmosphere?",
    answers_ja: ["酸素", "窒素", "二酸化炭素", "水素"],
    answers_en: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "磁石のN極が指す方角はどれですか？",
    question_en: "Which direction does the N-pole of a magnet point to?",
    answers_ja: ["南", "東", "西", "北"],
    answers_en: ["South", "East", "West", "North"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "植物が光合成で作り出すものは何ですか？",
    question_en: "What do plants produce through photosynthesis?",
    answers_ja: ["二酸化炭素", "窒素", "酸素と栄養分", "水素"],
    answers_en: [
      "Carbon dioxide",
      "Nitrogen",
      "Oxygen and nutrients",
      "Hydrogen",
    ],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "雷が光ってから音が遅れて聞こえるのはなぜですか？",
    question_en: "Why do we hear thunder after seeing lightning?",
    answers_ja: [
      "光のほうが速いから",
      "音のほうが速いから",
      "雷が2回鳴るから",
      "気のせい",
    ],
    answers_en: [
      "Because light travels faster",
      "Because sound travels faster",
      "Because thunder strikes twice",
      "It's just your imagination",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "太陽系の惑星で「輪」があることで有名な惑星はどれですか？",
    question_en: "Which planet in the solar system is famous for its rings?",
    answers_ja: ["火星", "土星", "木星", "天王星"],
    answers_en: ["Mars", "Saturn", "Jupiter", "Uranus"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 生物 (29-38)
  {
    question_ja: "パンダの主な食べ物は何ですか？",
    question_en: "What is the main food of pandas?",
    answers_ja: ["果物", "魚", "昆虫", "笹（竹）"],
    answers_en: ["Fruits", "Fish", "Insects", "Bamboo"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "イルカは魚類ですか、哺乳類ですか？",
    question_en: "Are dolphins fish or mammals?",
    answers_ja: ["魚類", "哺乳類", "爬虫類", "両生類"],
    answers_en: ["Fish", "Mammals", "Reptiles", "Amphibians"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "昆虫の足は全部で何本ですか？",
    question_en: "How many legs does an insect have in total?",
    answers_ja: ["4本", "6本", "8本", "10本"],
    answers_en: ["4", "6", "8", "10"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "カエルの子どもは何と呼ばれますか？",
    question_en: "What is a baby frog called?",
    answers_ja: ["メダカ", "ヤゴ", "おたまじゃくし", "イモリ"],
    answers_en: ["Killifish", "Dragonfly larva", "Tadpole", "Newt"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "クモの足は全部で何本ですか？",
    question_en: "How many legs does a spider have in total?",
    answers_ja: ["6本", "10本", "12本", "8本"],
    answers_en: ["6", "10", "12", "8"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "世界で一番大きい動物は何ですか？",
    question_en: "What is the largest animal in the world?",
    answers_ja: ["アフリカゾウ", "シロナガスクジラ", "キリン", "ジンベエザメ"],
    answers_en: ["African elephant", "Blue whale", "Giraffe", "Whale shark"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "サケは川と海のどちらで生まれますか？",
    question_en: "Are salmon born in rivers or in the sea?",
    answers_ja: ["海", "湖", "池", "川"],
    answers_en: ["Sea", "Lake", "Pond", "River"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "桜の花びらは通常何枚ですか？（ソメイヨシノ）",
    question_en:
      "How many petals does a cherry blossom typically have (Somei Yoshino variety)?",
    answers_ja: ["3枚", "5枚", "7枚", "10枚"],
    answers_en: ["3", "5", "7", "10"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "ペンギンは空を飛べますか？",
    question_en: "Can penguins fly?",
    answers_ja: [
      "飛べる",
      "少しだけ飛べる",
      "飛べない",
      "子どものときだけ飛べる",
    ],
    answers_en: [
      "Yes, they can fly",
      "They can fly a little",
      "No, they cannot fly",
      "Only when they are young",
    ],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "キリンの首の骨の数は人間と比べてどうですか？",
    question_en:
      "How does the number of neck bones in a giraffe compare to a human?",
    answers_ja: ["人間より多い", "人間と同じ7個", "人間より少ない", "骨がない"],
    answers_en: [
      "More than humans",
      "Same as humans — 7",
      "Fewer than humans",
      "They have no bones",
    ],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 日本史 (39-46)
  {
    question_ja: "鎌倉幕府を開いた人物は誰ですか？",
    question_en: "Who established the Kamakura Shogunate?",
    answers_ja: ["源頼朝", "平清盛", "足利尊氏", "徳川家康"],
    answers_en: [
      "Minamoto no Yoritomo",
      "Taira no Kiyomori",
      "Ashikaga Takauji",
      "Tokugawa Ieyasu",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "江戸幕府を開いた人物は誰ですか？",
    question_en: "Who established the Edo Shogunate?",
    answers_ja: ["豊臣秀吉", "織田信長", "武田信玄", "徳川家康"],
    answers_en: [
      "Toyotomi Hideyoshi",
      "Oda Nobunaga",
      "Takeda Shingen",
      "Tokugawa Ieyasu",
    ],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "本能寺の変で討たれた武将は誰ですか？",
    question_en: "Which warlord was killed in the Incident at Honnoji Temple?",
    answers_ja: ["豊臣秀吉", "徳川家康", "織田信長", "武田信玄"],
    answers_en: [
      "Toyotomi Hideyoshi",
      "Tokugawa Ieyasu",
      "Oda Nobunaga",
      "Takeda Shingen",
    ],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「天下統一」を果たしたとされる戦国武将は誰ですか？",
    question_en: "Which Sengoku-era warlord is credited with unifying Japan?",
    answers_ja: ["織田信長", "徳川家康", "武田信玄", "豊臣秀吉"],
    answers_en: [
      "Oda Nobunaga",
      "Tokugawa Ieyasu",
      "Takeda Shingen",
      "Toyotomi Hideyoshi",
    ],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "聖徳太子が建てたとされるお寺はどれですか？",
    question_en: "Which temple is said to have been built by Prince Shotoku?",
    answers_ja: ["東大寺", "金閣寺", "法隆寺", "清水寺"],
    answers_en: ["Todai-ji", "Kinkaku-ji", "Horyu-ji", "Kiyomizu-dera"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "明治維新が起きたのは何年ですか？",
    question_en: "In what year did the Meiji Restoration take place?",
    answers_ja: ["1868年", "1853年", "1889年", "1912年"],
    answers_en: ["1868", "1853", "1889", "1912"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本最初のオリンピック出場は何年ですか？",
    question_en: "In what year did Japan first participate in the Olympics?",
    answers_ja: ["1896年", "1936年", "1912年", "1964年"],
    answers_en: ["1896", "1936", "1912", "1964"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "奈良の大仏がある寺はどこですか？",
    question_en: "Which temple houses the Great Buddha of Nara?",
    answers_ja: ["法隆寺", "東大寺", "薬師寺", "興福寺"],
    answers_en: ["Horyu-ji", "Todai-ji", "Yakushi-ji", "Kofuku-ji"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 日本文化 (47-53)
  {
    question_ja: "お正月に食べる伝統的な料理を何と言いますか？",
    question_en:
      "What is the traditional cuisine eaten during Japanese New Year called?",
    answers_ja: ["お雑煮", "すき焼き", "天ぷら", "おせち料理"],
    answers_en: [
      "Ozoni (rice cake soup)",
      "Sukiyaki",
      "Tempura",
      "Osechi ryori (New Year dishes)",
    ],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "七五三は何歳の子どものお祝いですか？",
    question_en:
      "At what ages is the Japanese 'Shichi-Go-San' ceremony celebrated?",
    answers_ja: [
      "1歳・3歳・5歳",
      "3歳・5歳・7歳",
      "5歳・7歳・9歳",
      "2歳・4歳・6歳",
    ],
    answers_en: [
      "Ages 1, 3, and 5",
      "Ages 3, 5, and 7",
      "Ages 5, 7, and 9",
      "Ages 2, 4, and 6",
    ],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "ひな祭りは何月何日ですか？",
    question_en:
      "On what date is 'Hina Matsuri' (Japanese Doll Festival) celebrated?",
    answers_ja: ["2月3日", "4月4日", "5月5日", "3月3日"],
    answers_en: ["February 3", "April 4", "May 5", "March 3"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "こどもの日は何月何日ですか？",
    question_en: "On what date is Children's Day celebrated in Japan?",
    answers_ja: ["3月3日", "4月4日", "5月5日", "6月6日"],
    answers_en: ["March 3", "April 4", "May 5", "June 6"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本の国技は何ですか？",
    question_en: "What is the national sport of Japan?",
    answers_ja: ["相撲", "柔道", "剣道", "空手"],
    answers_en: ["Sumo", "Judo", "Kendo", "Karate"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "茶道で使う粉末状のお茶を何と言いますか？",
    question_en:
      "What is the powdered tea used in the Japanese tea ceremony called?",
    answers_ja: ["煎茶", "ほうじ茶", "抹茶", "番茶"],
    answers_en: ["Sencha", "Hojicha", "Matcha", "Bancha"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本の国花とされることが多い花はどれですか？",
    question_en:
      "Which flower is most commonly regarded as the national flower of Japan?",
    answers_ja: ["ひまわり", "桜", "チューリップ", "バラ"],
    answers_en: ["Sunflower", "Cherry blossom", "Tulip", "Rose"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 言葉・漢字 (54-61)
  {
    question_ja: "「山」という漢字の読み方で正しいのはどれですか？",
    question_en: "What is the correct reading of the kanji '山' (mountain)?",
    answers_ja: ["かわ", "うみ", "もり", "やま"],
    answers_en: [
      "Kawa (river)",
      "Umi (sea)",
      "Mori (forest)",
      "Yama (mountain)",
    ],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja:
      "「犬」の反対の意味の動物として、よく対比されるのはどれですか？",
    question_en:
      "Which animal is most commonly contrasted with dogs in Japanese culture?",
    answers_ja: ["猫", "鳥", "馬", "牛"],
    answers_en: ["Cat", "Bird", "Horse", "Cow"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「雨」の読み方はどれですか？",
    question_en: "What is the correct reading of the kanji '雨' (rain)?",
    answers_ja: ["あめ", "かぜ", "ゆき", "くも"],
    answers_en: ["Ame (rain)", "Kaze (wind)", "Yuki (snow)", "Kumo (cloud)"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「上」の反対の意味の漢字はどれですか？",
    question_en: "Which kanji has the opposite meaning of '上' (up/above)?",
    answers_ja: ["右", "下", "左", "中"],
    answers_en: ["右 Right", "下 Down/Below", "左 Left", "中 Middle"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「赤」「青」「黄」のうち、信号機にないのはどれですか？",
    question_en:
      "Among 'red', 'blue', and 'yellow', which one is NOT missing from a traffic light?",
    answers_ja: ["赤", "青", "黄", "全部ある"],
    answers_en: ["Red", "Blue", "Yellow", "All of them are present"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「月」という漢字の読み方で正しいのはどれですか？",
    question_en: "What is the correct reading of the kanji '月' (moon)?",
    answers_ja: ["つき", "ほし", "ひ", "そら"],
    answers_en: ["Tsuki (moon)", "Hoshi (star)", "Hi (sun/fire)", "Sora (sky)"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "五十音の最初の文字は何ですか？",
    question_en:
      "What is the first character in the Japanese 'Gojuon' (fifty sounds) chart?",
    answers_ja: ["い", "う", "あ", "え"],
    answers_en: ["I", "U", "A", "E"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "アルファベットは全部で何文字ですか？",
    question_en: "How many letters are there in the alphabet?",
    answers_ja: ["24文字", "26文字", "28文字", "30文字"],
    answers_en: ["24 letters", "26 letters", "28 letters", "30 letters"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // ことわざ (62-68)
  {
    question_ja: "「猿も木から○○」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese proverb 'Even monkeys _____ from trees'?",
    answers_ja: ["飛ぶ", "登る", "降りる", "落ちる"],
    answers_en: ["Jump", "Climb", "Come down", "Fall"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「犬も歩けば○○に当たる」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese proverb 'Even a dog, if it walks, will bump into a _____'?",
    answers_ja: ["棒", "石", "壁", "人"],
    answers_en: ["Stick", "Stone", "Wall", "Person"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「花より○○」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese proverb 'Rather than flowers, _____' (substance over beauty)?",
    answers_ja: ["月", "団子", "酒", "風"],
    answers_en: ["The moon", "Dumplings", "Sake", "The wind"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「三日○○」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese expression 'Three-day _____' (someone who gives up quickly)?",
    answers_ja: ["天下", "大名", "坊主", "小僧"],
    answers_en: ["Ruler", "Lord", "Monk", "Young boy"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「早起きは三文の○○」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese proverb 'The early bird gets three coins worth of _____'?",
    answers_ja: ["損", "得", "徳", "福"],
    answers_en: ["Loss", "Gain", "Virtue/Gain", "Fortune"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「石の上にも○○」の○○に入る言葉は？",
    question_en:
      "What completes the Japanese proverb 'Sit on a stone for _____' (patience pays off)?",
    answers_ja: ["三年", "一年", "二年", "五年"],
    answers_en: ["Three years", "One year", "Two years", "Five years"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「塵も積もれば○○となる」の○○に入る言葉は？",
    question_en:
      "What word completes the Japanese proverb 'Even dust, piled up, becomes a _____'?",
    answers_ja: ["海", "川", "丘", "山"],
    answers_en: ["Sea", "River", "Hill", "Mountain"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  // スポーツ (69-76)
  {
    question_ja: "サッカーは1チーム何人でプレーしますか？",
    question_en: "How many players are on a soccer team?",
    answers_ja: ["9人", "10人", "11人", "12人"],
    answers_en: ["9 players", "10 players", "11 players", "12 players"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "野球は1チーム何人でプレーしますか？",
    question_en: "How many players are on a baseball team (on the field)?",
    answers_ja: ["8人", "9人", "10人", "11人"],
    answers_en: ["8 players", "9 players", "10 players", "11 players"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "バスケットボールは1チーム何人でプレーしますか？",
    question_en: "How many players are on a basketball team (on the court)?",
    answers_ja: ["5人", "4人", "6人", "7人"],
    answers_en: ["5 players", "4 players", "6 players", "7 players"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "オリンピックは何年ごとに開催されますか？",
    question_en: "How often are the Olympic Games held?",
    answers_ja: ["2年ごと", "3年ごと", "4年ごと", "5年ごと"],
    answers_en: [
      "Every 2 years",
      "Every 3 years",
      "Every 4 years",
      "Every 5 years",
    ],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "マラソンの距離は約何キロメートルですか？",
    question_en:
      "What is the approximate distance of a marathon in kilometers?",
    answers_ja: ["約32km", "約52km", "約62km", "約42km"],
    answers_en: ["About 32 km", "About 52 km", "About 62 km", "About 42 km"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "テニスで得点が0のことを何と言いますか？",
    question_en: "What is a score of zero called in tennis?",
    answers_ja: ["ラブ", "ゼロ", "ナッシング", "ブランク"],
    answers_en: ["Love", "Zero", "Nothing", "Blank"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "大相撲の最高位は何ですか？",
    question_en: "What is the highest rank in professional sumo wrestling?",
    answers_ja: ["大関", "横綱", "関脇", "小結"],
    answers_en: ["Ozeki", "Yokozuna", "Sekiwake", "Komusubi"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "ボウリングのピンは全部で何本ですか？",
    question_en: "How many pins are there in bowling?",
    answers_ja: ["8本", "12本", "10本", "15本"],
    answers_en: ["8 pins", "12 pins", "10 pins", "15 pins"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  // 食・生活 (77-84)
  {
    question_ja: "お米を炊く前に行う作業は何ですか？",
    question_en: "What do you do to rice before cooking it?",
    answers_ja: ["焼く", "揚げる", "蒸す", "研ぐ（とぐ）"],
    answers_en: ["Grill it", "Deep-fry it", "Steam it", "Rinse/wash it"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "味噌汁の主な原料は何ですか？",
    question_en: "What is the main ingredient of miso soup?",
    answers_ja: ["醤油", "味噌", "塩", "酢"],
    answers_en: ["Soy sauce", "Miso paste", "Salt", "Vinegar"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "お寿司に使われる酢飯の「酢」は何からできていますか？",
    question_en: "What is the vinegar used in sushi rice primarily made from?",
    answers_ja: ["小麦", "米", "大豆", "とうもろこし"],
    answers_en: ["Wheat", "Rice", "Soybeans", "Corn"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "豆腐の原料は何ですか？",
    question_en: "What is tofu made from?",
    answers_ja: ["小麦", "米", "大豆", "そば"],
    answers_en: ["Wheat", "Rice", "Soybeans", "Buckwheat"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "カレーライスの「ライス」とは何のことですか？",
    question_en: "What does 'rice' refer to in 'curry rice'?",
    answers_ja: ["ご飯", "パン", "麺", "芋"],
    answers_en: ["Steamed rice", "Bread", "Noodles", "Potatoes"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "日本で一番多く生産されている果物はどれですか？",
    question_en: "Which fruit is produced the most in Japan?",
    answers_ja: ["りんご", "ぶどう", "もも", "みかん"],
    answers_en: ["Apples", "Grapes", "Peaches", "Mandarin oranges"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「醤油」の原料に含まれるのはどれですか？",
    question_en: "Which of the following is an ingredient of soy sauce?",
    answers_ja: ["牛乳", "卵", "大豆", "砂糖"],
    answers_en: ["Milk", "Eggs", "Soybeans", "Sugar"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "納豆は何を発酵させた食べ物ですか？",
    question_en: "What is natto (a fermented food) made by fermenting?",
    answers_ja: ["大豆", "米", "小麦", "とうもろこし"],
    answers_en: ["Soybeans", "Rice", "Wheat", "Corn"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  // 算数・数学の基礎 (85-93)
  {
    question_ja: "三角形の内角の和は何度ですか？",
    question_en: "What is the sum of the interior angles of a triangle?",
    answers_ja: ["90度", "180度", "270度", "360度"],
    answers_en: ["90 degrees", "180 degrees", "270 degrees", "360 degrees"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "四角形の内角の和は何度ですか？",
    question_en: "What is the sum of the interior angles of a quadrilateral?",
    answers_ja: ["180度", "270度", "360度", "450度"],
    answers_en: ["180 degrees", "270 degrees", "360 degrees", "450 degrees"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "1キログラムは何グラムですか？",
    question_en: "How many grams are in one kilogram?",
    answers_ja: ["10グラム", "100グラム", "10000グラム", "1000グラム"],
    answers_en: ["10 grams", "100 grams", "10,000 grams", "1,000 grams"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "1メートルは何センチメートルですか？",
    question_en: "How many centimeters are in one meter?",
    answers_ja: ["100cm", "10cm", "1000cm", "10000cm"],
    answers_en: ["100 cm", "10 cm", "1,000 cm", "10,000 cm"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "1時間は何分ですか？",
    question_en: "How many minutes are in one hour?",
    answers_ja: ["30分", "60分", "45分", "100分"],
    answers_en: ["30 minutes", "60 minutes", "45 minutes", "100 minutes"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "円の形をした図形の周りの長さを何と言いますか？",
    question_en: "What is the perimeter of a circle called?",
    answers_ja: ["面積", "直径", "半径", "円周"],
    answers_en: ["Area", "Diameter", "Radius", "Circumference"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "2の3乗はいくつですか？",
    question_en: "What is 2 to the power of 3?",
    answers_ja: ["6", "8", "9", "12"],
    answers_en: ["6", "8", "9", "12"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  {
    question_ja: "1キロメートルは何メートルですか？",
    question_en: "How many meters are in one kilometer?",
    answers_ja: ["10m", "100m", "1000m", "10000m"],
    answers_en: ["10 m", "100 m", "1,000 m", "10,000 m"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "偶数でないのはどれですか？",
    question_en: "Which of the following is NOT an even number?",
    answers_ja: ["2", "7", "4", "10"],
    answers_en: ["2", "7", "4", "10"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
  // 音楽・エンタメ基礎 (94-100)
  {
    question_ja: "ドレミファソラシドの「ド」は英語で何と言いますか？",
    question_en:
      "In the solfege scale 'Do Re Mi Fa Sol La Si Do', what is 'Do' called in English note names?",
    answers_ja: ["A", "B", "C", "D"],
    answers_en: ["A", "B", "C", "D"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "ピアノの鍵盤で白い鍵と黒い鍵、多いのはどちらですか？",
    question_en:
      "On a piano keyboard, are there more white keys or black keys?",
    answers_ja: ["白い鍵", "黒い鍵", "同じ数", "ピアノによる"],
    answers_en: [
      "White keys",
      "Black keys",
      "They are equal",
      "It depends on the piano",
    ],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「桃太郎」でお供にならなかった動物はどれですか？",
    question_en:
      "In the Japanese folktale 'Momotaro', which animal did NOT accompany him?",
    answers_ja: ["猫", "犬", "猿", "キジ"],
    answers_en: ["Cat", "Dog", "Monkey", "Pheasant"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「浦島太郎」が助けた動物は何ですか？",
    question_en:
      "In the Japanese folktale 'Urashima Taro', which animal did he rescue?",
    answers_ja: ["鶴", "魚", "ウサギ", "亀"],
    answers_en: ["Crane", "Fish", "Rabbit", "Turtle"],
    correctIndex: 3,
    difficulty: "easy" as const,
  },
  {
    question_ja: "「かぐや姫」はどこから生まれましたか？",
    question_en:
      "In the Japanese folktale 'Kaguya-hime', where was she born from?",
    answers_ja: ["竹", "桃", "栗", "柿"],
    answers_en: ["Bamboo", "Peach", "Chestnut", "Persimmon"],
    correctIndex: 0,
    difficulty: "easy" as const,
  },
  {
    question_ja: "音楽の「四分音符」は「八分音符」何個分の長さですか？",
    question_en: "A quarter note is equal to how many eighth notes in length?",
    answers_ja: ["1個分", "3個分", "2個分", "4個分"],
    answers_en: ["1", "3", "2", "4"],
    correctIndex: 2,
    difficulty: "easy" as const,
  },
  {
    question_ja: "ギターの弦は一般的に何本ですか？",
    question_en: "How many strings does a standard guitar have?",
    answers_ja: ["4本", "6本", "5本", "8本"],
    answers_en: ["4 strings", "6 strings", "5 strings", "8 strings"],
    correctIndex: 1,
    difficulty: "easy" as const,
  },
];
