export const mediumQuestions = [
  // ===== 世界地理・国際知識 =====
  {
    question: "世界で最も面積が大きい湖はどれか？",
    answers: ["カスピ海", "スペリオル湖", "バイカル湖", "ヴィクトリア湖"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "アフリカ大陸で最も人口が多い国はどれか？",
    answers: ["エジプト", "ナイジェリア", "南アフリカ", "エチオピア"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "国際連合の安全保障理事会の常任理事国でないのはどれか？",
    answers: ["フランス", "中国", "ドイツ", "ロシア"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "南米大陸で面積が最も大きい国はどれか？",
    answers: ["アルゼンチン", "コロンビア", "ペルー", "ブラジル"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "スエズ運河はどの国に位置しているか？",
    answers: ["エジプト", "トルコ", "パナマ", "イラク"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "世界で最も長い川はどれか？",
    answers: ["アマゾン川", "ナイル川", "長江", "ミシシッピ川"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "EUの本部が置かれている都市はどこか？",
    answers: ["パリ", "アムステルダム", "ブリュッセル", "ベルリン"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "世界で最も小さい国はどれか？",
    answers: ["モナコ", "サンマリノ", "リヒテンシュタイン", "バチカン市国"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "赤道が通過しない国はどれか？",
    answers: ["南アフリカ", "ブラジル", "インドネシア", "コンゴ"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "地中海に面していない国はどれか？",
    answers: ["トルコ", "スイス", "イタリア", "スペイン"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "ASEAN（東南アジア諸国連合）の加盟国数はいくつか？",
    answers: ["8か国", "9か国", "10か国", "12か国"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "世界遺産「マチュ・ピチュ」がある国はどこか？",
    answers: ["ボリビア", "チリ", "コロンビア", "ペルー"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 世界史 / 日本近代史 =====
  {
    question: "ベルリンの壁が崩壊したのは西暦何年か？",
    answers: ["1989年", "1991年", "1987年", "1990年"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "日露戦争の講和条約はどれか？",
    answers: [
      "ヴェルサイユ条約",
      "ポーツマス条約",
      "下関条約",
      "サンフランシスコ講和条約",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "第一次世界大戦の引き金となった事件はどれか？",
    answers: [
      "ボストン茶会事件",
      "真珠湾攻撃",
      "サラエボ事件",
      "ベルリンの壁崩壊",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "明治維新で「五箇条の御誓文」が発布された年はいつか？",
    answers: ["1853年", "1858年", "1871年", "1868年"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "古代ローマ帝国を東西に分裂させた皇帝は誰か？",
    answers: [
      "テオドシウス1世",
      "コンスタンティヌス",
      "ネロ",
      "アウグストゥス",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "日本で最初の内閣総理大臣は誰か？",
    answers: ["大隈重信", "伊藤博文", "山県有朋", "西園寺公望"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "ルネサンスが最初に花開いた国はどこか？",
    answers: ["フランス", "ドイツ", "イタリア", "スペイン"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "廃藩置県が行われたのは何年か？",
    answers: ["1868年", "1869年", "1873年", "1871年"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "マグナ・カルタ（大憲章）が制定された国はどこか？",
    answers: ["イギリス", "フランス", "ドイツ", "イタリア"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question:
      "日本が国際連盟を脱退するきっかけとなった報告書を作成した調査団の名前は？",
    answers: [
      "マッカーサー調査団",
      "リットン調査団",
      "ポツダム調査団",
      "ヤルタ調査団",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "アメリカ独立宣言が採択された年はいつか？",
    answers: ["1789年", "1783年", "1776年", "1770年"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "日清戦争の講和条約はどれか？",
    answers: ["ポーツマス条約", "南京条約", "天津条約", "下関条約"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 物理・化学 =====
  {
    question: "水の化学式はH2Oだが、過酸化水素の化学式はどれか？",
    answers: ["H2O2", "HO2", "H3O", "H2O3"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "絶対零度は摂氏何度か？",
    answers: ["-100℃", "-273.15℃", "-300℃", "-200℃"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "音の速さ（空気中、常温）に最も近いのはどれか？",
    answers: ["約170m/s", "約240m/s", "約340m/s", "約500m/s"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "周期表で原子番号1の元素は何か？",
    answers: ["ヘリウム", "リチウム", "炭素", "水素"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "電気抵抗の単位はどれか？",
    answers: ["オーム（Ω）", "アンペア（A）", "ボルト（V）", "ワット（W）"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ニュートンの運動の第二法則を表す式はどれか？",
    answers: ["E=mc²", "F=ma", "PV=nRT", "V=IR"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "ダイヤモンドと同じ元素からなる鉱物はどれか？",
    answers: ["石英", "方解石", "黒鉛（グラファイト）", "雲母"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "希ガス（貴ガス）に分類されないのはどれか？",
    answers: ["ヘリウム", "ネオン", "アルゴン", "窒素"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "酸性の水溶液のpHの範囲はどれか？",
    answers: ["7より小さい", "ちょうど7", "7より大きい", "14"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "地球の重力加速度に最も近い値はどれか？",
    answers: ["約5.8m/s²", "約9.8m/s²", "約12.5m/s²", "約15.0m/s²"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "鉄の元素記号はどれか？",
    answers: ["Ir", "Fr", "Fe", "Fi"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 文学・芸術（日本/世界） =====
  {
    question: "『変身』の作者は誰か？",
    answers: ["トルストイ", "ドストエフスキー", "ヘミングウェイ", "カフカ"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "『枕草子』の作者は誰か？",
    answers: ["清少納言", "紫式部", "和泉式部", "小野小町"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "「叫び」で有名な画家は誰か？",
    answers: ["ゴッホ", "ムンク", "ピカソ", "ダリ"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "芥川龍之介の代表作はどれか？",
    answers: ["坊っちゃん", "雪国", "羅生門", "人間失格"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "『老人と海』の作者は誰か？",
    answers: [
      "マーク・トウェイン",
      "フィッツジェラルド",
      "スタインベック",
      "ヘミングウェイ",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "「印象・日の出」を描いた画家は誰か？",
    answers: ["モネ", "ルノワール", "セザンヌ", "マネ"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "『罪と罰』の作者は誰か？",
    answers: ["トルストイ", "ドストエフスキー", "チェーホフ", "ゴーゴリ"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "夏目漱石の作品でないものはどれか？",
    answers: ["坊っちゃん", "吾輩は猫である", "舞姫", "こころ"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "「ゲルニカ」を描いた画家は誰か？",
    answers: ["ダリ", "ミロ", "マティス", "ピカソ"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "『万葉集』に最も多くの歌を残した歌人は誰か？",
    answers: ["大伴家持", "柿本人麻呂", "山上憶良", "額田王"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ノーベル文学賞を受賞した日本人作家はどれか？",
    answers: ["三島由紀夫", "川端康成", "太宰治", "芥川龍之介"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "『ハムレット』を書いた劇作家は誰か？",
    answers: ["モリエール", "ゲーテ", "シェイクスピア", "チェーホフ"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 政治・経済・法律の基礎 =====
  {
    question: "日本の衆議院議員の任期は何年か？",
    answers: ["3年", "5年", "6年", "4年"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "日本銀行の主な役割として正しいのはどれか？",
    answers: [
      "通貨の発行と金融政策の実施",
      "国防の管理",
      "外交交渉",
      "法律の制定",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "GDPとは何の略称か？",
    answers: [
      "General Domestic Production",
      "Gross Domestic Product",
      "Global Development Program",
      "Government Debt Policy",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "三権分立の「三権」に含まれないものはどれか？",
    answers: ["立法権", "司法権", "報道権", "行政権"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "日本の参議院議員の任期は何年か？",
    answers: ["3年", "4年", "5年", "6年"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "インフレーションとはどのような現象か？",
    answers: [
      "物価が持続的に上昇すること",
      "物価が持続的に下落すること",
      "為替レートが変動すること",
      "失業率が上昇すること",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "日本の最高裁判所の裁判官の人数は何人か？",
    answers: ["9人", "15人", "11人", "21人"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question:
      "日本国憲法で保障される「国民の三大義務」に含まれないのはどれか？",
    answers: ["勤労の義務", "納税の義務", "投票の義務", "教育を受けさせる義務"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "需要と供給の法則で、需要が増加すると一般的に価格はどうなるか？",
    answers: ["変わらない", "下がる", "不安定になる", "上がる"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "日本の選挙権年齢は何歳以上か？",
    answers: ["18歳以上", "20歳以上", "16歳以上", "25歳以上"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "日本の内閣総理大臣を指名するのはどの機関か？",
    answers: ["天皇", "国会", "最高裁判所", "内閣"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "累進課税制度の特徴はどれか？",
    answers: [
      "全員同じ税率",
      "所得が低いほど税率が高い",
      "所得が高いほど税率が高い",
      "税金がかからない",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 生物・医学 =====
  {
    question: "ヒトの体内で最も大きな臓器はどれか？",
    answers: ["脳", "心臓", "肺", "肝臓"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "光合成を行う細胞内の構造体はどれか？",
    answers: ["葉緑体", "ミトコンドリア", "リボソーム", "ゴルジ体"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ヒトの血液型で、ABO式の型を決定するのは何か？",
    answers: ["白血球", "赤血球の表面抗原", "血小板", "血漿タンパク質"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "ヒトの染色体の数は何本か？",
    answers: ["23本", "44本", "46本", "48本"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "インスリンを分泌する臓器はどれか？",
    answers: ["肝臓", "腎臓", "甲状腺", "膵臓"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "細胞のエネルギー通貨と呼ばれる物質はどれか？",
    answers: ["ATP", "DNA", "RNA", "タンパク質"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ヒトの小腸の主な役割はどれか？",
    answers: ["食物の貯蔵", "栄養素の吸収", "水分の吸収", "食物の粉砕"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "遺伝情報の伝達で、DNAからmRNAを作る過程を何というか？",
    answers: ["翻訳", "複製", "転写", "変異"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "抗体を産生する細胞はどれか？",
    answers: ["赤血球", "血小板", "マクロファージ", "B細胞（形質細胞）"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "メンデルの法則で、対立遺伝子が分離する法則を何というか？",
    answers: ["分離の法則", "独立の法則", "優性の法則", "連鎖の法則"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ヒトの体温調節の中枢はどこにあるか？",
    answers: ["大脳", "視床下部", "小脳", "延髄"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "植物の気孔の主な役割はどれか？",
    answers: ["光の吸収", "水の吸収", "ガス交換と蒸散", "養分の貯蔵"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 数学 =====
  {
    question: "円周率πの値に最も近いのはどれか？",
    answers: ["2.718", "3.000", "3.333", "3.141"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "1から100までの自然数の合計はいくつか？",
    answers: ["5050", "4950", "5500", "5100"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "2の10乗はいくつか？",
    answers: ["512", "1024", "2048", "256"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "直角三角形の斜辺の長さを求める定理はどれか？",
    answers: ["フェルマーの定理", "中間値の定理", "三平方の定理", "余弦定理"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "素数でないものはどれか？",
    answers: ["2", "17", "23", "27"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "log₁₀(1000)の値はいくつか？",
    answers: ["3", "10", "100", "30"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "正六角形の内角の和は何度か？",
    answers: ["360度", "720度", "540度", "900度"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "虚数単位iの定義として正しいのはどれか？",
    answers: ["i = -1", "i = 0", "i² = -1", "i² = 1"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "フィボナッチ数列の最初の7項（1,1,2,3,5,8,?）の?に入る数は？",
    answers: ["10", "11", "12", "13"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "球の体積を求める公式はどれか？",
    answers: ["(4/3)πr³", "4πr²", "πr²h", "2πr"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "階乗「5!」の値はいくつか？",
    answers: ["60", "120", "24", "720"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "sin 30°の値はいくつか？",
    answers: ["1", "√3/2", "1/2", "√2/2"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "自然対数の底eの値に最も近いのはどれか？",
    answers: ["1.414", "2.236", "3.141", "2.718"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 音楽・映画・文化 =====
  {
    question: "「運命」（交響曲第5番）を作曲したのは誰か？",
    answers: ["ベートーヴェン", "モーツァルト", "バッハ", "ショパン"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "映画『ローマの休日』の主演女優は誰か？",
    answers: [
      "マリリン・モンロー",
      "オードリー・ヘプバーン",
      "エリザベス・テイラー",
      "グレース・ケリー",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "日本の伝統芸能「歌舞伎」の創始者とされるのは誰か？",
    answers: ["世阿弥", "近松門左衛門", "出雲阿国", "観阿弥"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question:
      "映画『スター・ウォーズ』シリーズの監督（オリジナル三部作）は誰か？",
    answers: [
      "スティーブン・スピルバーグ",
      "ジェームズ・キャメロン",
      "リドリー・スコット",
      "ジョージ・ルーカス",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "ピアノの鍵盤は全部で何鍵あるか（標準的なグランドピアノ）？",
    answers: ["88鍵", "76鍵", "92鍵", "84鍵"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "「四季」を作曲したイタリアの作曲家は誰か？",
    answers: ["パガニーニ", "ヴィヴァルディ", "ヴェルディ", "プッチーニ"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "日本の国技とされる相撲で、最高位の力士の称号は何か？",
    answers: ["大関", "関脇", "横綱", "小結"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "アカデミー賞の通称は何か？",
    answers: ["グラミー賞", "エミー賞", "トニー賞", "オスカー"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "「ボヘミアン・ラプソディ」を歌ったバンドはどれか？",
    answers: [
      "クイーン",
      "ビートルズ",
      "レッド・ツェッペリン",
      "ローリング・ストーンズ",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "茶道の三千家に含まれないのはどれか？",
    answers: ["表千家", "裏千家", "遠州流", "武者小路千家"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "映画『千と千尋の神隠し』の監督は誰か？",
    answers: ["細田守", "宮崎駿", "新海誠", "高畑勲"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "音楽用語で「フォルテ（forte）」はどのような意味か？",
    answers: ["遅く", "速く", "弱く", "強く"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question: "太陽系で最も大きい惑星はどれか？",
    answers: ["木星", "土星", "天王星", "海王星"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question: "ノーベル賞の授賞式が行われる都市はどこか？（平和賞を除く）",
    answers: ["ジュネーブ", "ストックホルム", "コペンハーゲン", "ヘルシンキ"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question: "日本の都道府県で最も面積が大きいのはどこか？",
    answers: ["岩手県", "長野県", "北海道", "新潟県"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question: "「白鳥の湖」を作曲したのは誰か？",
    answers: [
      "ストラヴィンスキー",
      "ラフマニノフ",
      "リムスキー＝コルサコフ",
      "チャイコフスキー",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
];
