export const mediumQuestions = [
  // ===== 世界地理・国際知識 =====
  {
    question_ja: "世界で最も面積が大きい湖はどれか？",
    question_en: "Which is the largest lake in the world by area?",
    answers_ja: ["カスピ海", "スペリオル湖", "バイカル湖", "ヴィクトリア湖"],
    answers_en: [
      "Caspian Sea",
      "Lake Superior",
      "Lake Baikal",
      "Lake Victoria",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "アフリカ大陸で最も人口が多い国はどれか？",
    question_en: "Which country has the largest population in Africa?",
    answers_ja: ["エジプト", "ナイジェリア", "南アフリカ", "エチオピア"],
    answers_en: ["Egypt", "Nigeria", "South Africa", "Ethiopia"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "国際連合の安全保障理事会の常任理事国でないのはどれか？",
    question_en:
      "Which of the following is NOT a permanent member of the UN Security Council?",
    answers_ja: ["フランス", "中国", "ドイツ", "ロシア"],
    answers_en: ["France", "China", "Germany", "Russia"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "南米大陸で面積が最も大きい国はどれか？",
    question_en: "Which is the largest country in South America by area?",
    answers_ja: ["アルゼンチン", "コロンビア", "ペルー", "ブラジル"],
    answers_en: ["Argentina", "Colombia", "Peru", "Brazil"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "スエズ運河はどの国に位置しているか？",
    question_en: "In which country is the Suez Canal located?",
    answers_ja: ["エジプト", "トルコ", "パナマ", "イラク"],
    answers_en: ["Egypt", "Turkey", "Panama", "Iraq"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "世界で最も長い川はどれか？",
    question_en: "Which is the longest river in the world?",
    answers_ja: ["アマゾン川", "ナイル川", "長江", "ミシシッピ川"],
    answers_en: [
      "Amazon River",
      "Nile River",
      "Yangtze River",
      "Mississippi River",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "EUの本部が置かれている都市はどこか？",
    question_en: "In which city is the headquarters of the EU located?",
    answers_ja: ["パリ", "アムステルダム", "ブリュッセル", "ベルリン"],
    answers_en: ["Paris", "Amsterdam", "Brussels", "Berlin"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "世界で最も小さい国はどれか？",
    question_en: "Which is the smallest country in the world?",
    answers_ja: ["モナコ", "サンマリノ", "リヒテンシュタイン", "バチカン市国"],
    answers_en: ["Monaco", "San Marino", "Liechtenstein", "Vatican City"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "赤道が通過しない国はどれか？",
    question_en: "Which country does the equator NOT pass through?",
    answers_ja: ["南アフリカ", "ブラジル", "インドネシア", "コンゴ"],
    answers_en: ["South Africa", "Brazil", "Indonesia", "Congo"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "地中海に面していない国はどれか？",
    question_en: "Which country does NOT border the Mediterranean Sea?",
    answers_ja: ["トルコ", "スイス", "イタリア", "スペイン"],
    answers_en: ["Turkey", "Switzerland", "Italy", "Spain"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ASEAN（東南アジア諸国連合）の加盟国数はいくつか？",
    question_en: "How many member countries does ASEAN have?",
    answers_ja: ["8か国", "9か国", "10か国", "12か国"],
    answers_en: ["8 countries", "9 countries", "10 countries", "12 countries"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "世界遺産「マチュ・ピチュ」がある国はどこか？",
    question_en:
      "In which country is the World Heritage Site Machu Picchu located?",
    answers_ja: ["ボリビア", "チリ", "コロンビア", "ペルー"],
    answers_en: ["Bolivia", "Chile", "Colombia", "Peru"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 世界史 / 日本近代史 =====
  {
    question_ja: "ベルリンの壁が崩壊したのは西暦何年か？",
    question_en: "In what year did the Berlin Wall fall?",
    answers_ja: ["1989年", "1991年", "1987年", "1990年"],
    answers_en: ["1989", "1991", "1987", "1990"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日露戦争の講和条約はどれか？",
    question_en: "Which treaty ended the Russo-Japanese War?",
    answers_ja: [
      "ヴェルサイユ条約",
      "ポーツマス条約",
      "下関条約",
      "サンフランシスコ講和条約",
    ],
    answers_en: [
      "Treaty of Versailles",
      "Treaty of Portsmouth",
      "Treaty of Shimonoseki",
      "Treaty of San Francisco",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "第一次世界大戦の引き金となった事件はどれか？",
    question_en: "Which event triggered World War I?",
    answers_ja: [
      "ボストン茶会事件",
      "真珠湾攻撃",
      "サラエボ事件",
      "ベルリンの壁崩壊",
    ],
    answers_en: [
      "Boston Tea Party",
      "Attack on Pearl Harbor",
      "Assassination in Sarajevo",
      "Fall of the Berlin Wall",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "明治維新で「五箇条の御誓文」が発布された年はいつか？",
    question_en:
      "In what year was the Charter Oath (Five Articles Oath) proclaimed during the Meiji Restoration?",
    answers_ja: ["1853年", "1858年", "1871年", "1868年"],
    answers_en: ["1853", "1858", "1871", "1868"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "古代ローマ帝国を東西に分裂させた皇帝は誰か？",
    question_en: "Which emperor divided the Roman Empire into East and West?",
    answers_ja: [
      "テオドシウス1世",
      "コンスタンティヌス",
      "ネロ",
      "アウグストゥス",
    ],
    answers_en: ["Theodosius I", "Constantine", "Nero", "Augustus"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本で最初の内閣総理大臣は誰か？",
    question_en: "Who was the first Prime Minister of Japan?",
    answers_ja: ["大隈重信", "伊藤博文", "山県有朋", "西園寺公望"],
    answers_en: [
      "Okuma Shigenobu",
      "Ito Hirobumi",
      "Yamagata Aritomo",
      "Saionji Kinmochi",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ルネサンスが最初に花開いた国はどこか？",
    question_en: "In which country did the Renaissance first flourish?",
    answers_ja: ["フランス", "ドイツ", "イタリア", "スペイン"],
    answers_en: ["France", "Germany", "Italy", "Spain"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "廃藩置県が行われたのは何年か？",
    question_en:
      "In what year was the abolition of feudal domains and establishment of prefectures carried out in Japan?",
    answers_ja: ["1868年", "1869年", "1873年", "1871年"],
    answers_en: ["1868", "1869", "1873", "1871"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "マグナ・カルタ（大憲章）が制定された国はどこか？",
    question_en: "In which country was the Magna Carta established?",
    answers_ja: ["イギリス", "フランス", "ドイツ", "イタリア"],
    answers_en: ["England", "France", "Germany", "Italy"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja:
      "日本が国際連盟を脱退するきっかけとなった報告書を作成した調査団の名前は？",
    question_en:
      "What was the name of the commission whose report led Japan to withdraw from the League of Nations?",
    answers_ja: [
      "マッカーサー調査団",
      "リットン調査団",
      "ポツダム調査団",
      "ヤルタ調査団",
    ],
    answers_en: [
      "MacArthur Commission",
      "Lytton Commission",
      "Potsdam Commission",
      "Yalta Commission",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "アメリカ独立宣言が採択された年はいつか？",
    question_en:
      "In what year was the United States Declaration of Independence adopted?",
    answers_ja: ["1789年", "1783年", "1776年", "1770年"],
    answers_en: ["1789", "1783", "1776", "1770"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日清戦争の講和条約はどれか？",
    question_en: "Which treaty ended the First Sino-Japanese War?",
    answers_ja: ["ポーツマス条約", "南京条約", "天津条約", "下関条約"],
    answers_en: [
      "Treaty of Portsmouth",
      "Treaty of Nanking",
      "Treaty of Tientsin",
      "Treaty of Shimonoseki",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 物理・化学 =====
  {
    question_ja: "水の化学式はH2Oだが、過酸化水素の化学式はどれか？",
    question_en:
      "The chemical formula for water is H2O. What is the chemical formula for hydrogen peroxide?",
    answers_ja: ["H2O2", "HO2", "H3O", "H2O3"],
    answers_en: ["H2O2", "HO2", "H3O", "H2O3"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "絶対零度は摂氏何度か？",
    question_en: "What is absolute zero in degrees Celsius?",
    answers_ja: ["-100℃", "-273.15℃", "-300℃", "-200℃"],
    answers_en: ["-100°C", "-273.15°C", "-300°C", "-200°C"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "音の速さ（空気中、常温）に最も近いのはどれか？",
    question_en:
      "Which is closest to the speed of sound in air at room temperature?",
    answers_ja: ["約170m/s", "約240m/s", "約340m/s", "約500m/s"],
    answers_en: [
      "About 170 m/s",
      "About 240 m/s",
      "About 340 m/s",
      "About 500 m/s",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "周期表で原子番号1の元素は何か？",
    question_en:
      "What is the element with atomic number 1 on the periodic table?",
    answers_ja: ["ヘリウム", "リチウム", "炭素", "水素"],
    answers_en: ["Helium", "Lithium", "Carbon", "Hydrogen"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "電気抵抗の単位はどれか？",
    question_en: "What is the unit of electrical resistance?",
    answers_ja: ["オーム（Ω）", "アンペア（A）", "ボルト（V）", "ワット（W）"],
    answers_en: ["Ohm (Ω)", "Ampere (A)", "Volt (V)", "Watt (W)"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ニュートンの運動の第二法則を表す式はどれか？",
    question_en: "Which equation represents Newton's second law of motion?",
    answers_ja: ["E=mc²", "F=ma", "PV=nRT", "V=IR"],
    answers_en: ["E=mc²", "F=ma", "PV=nRT", "V=IR"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ダイヤモンドと同じ元素からなる鉱物はどれか？",
    question_en: "Which mineral is made of the same element as diamond?",
    answers_ja: ["石英", "方解石", "黒鉛（グラファイト）", "雲母"],
    answers_en: ["Quartz", "Calcite", "Graphite", "Mica"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "希ガス（貴ガス）に分類されないのはどれか？",
    question_en: "Which of the following is NOT classified as a noble gas?",
    answers_ja: ["ヘリウム", "ネオン", "アルゴン", "窒素"],
    answers_en: ["Helium", "Neon", "Argon", "Nitrogen"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "酸性の水溶液のpHの範囲はどれか？",
    question_en: "What is the pH range of an acidic solution?",
    answers_ja: ["7より小さい", "ちょうど7", "7より大きい", "14"],
    answers_en: ["Less than 7", "Exactly 7", "Greater than 7", "14"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "地球の重力加速度に最も近い値はどれか？",
    question_en:
      "Which value is closest to Earth's gravitational acceleration?",
    answers_ja: ["約5.8m/s²", "約9.8m/s²", "約12.5m/s²", "約15.0m/s²"],
    answers_en: [
      "About 5.8 m/s²",
      "About 9.8 m/s²",
      "About 12.5 m/s²",
      "About 15.0 m/s²",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "鉄の元素記号はどれか？",
    question_en: "What is the chemical symbol for iron?",
    answers_ja: ["Ir", "Fr", "Fe", "Fi"],
    answers_en: ["Ir", "Fr", "Fe", "Fi"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 文学・芸術（日本/世界） =====
  {
    question_ja: "『変身』の作者は誰か？",
    question_en: "Who is the author of 'The Metamorphosis'?",
    answers_ja: ["トルストイ", "ドストエフスキー", "ヘミングウェイ", "カフカ"],
    answers_en: ["Tolstoy", "Dostoevsky", "Hemingway", "Kafka"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "『枕草子』の作者は誰か？",
    question_en:
      "Who is the author of 'The Pillow Book', a classic work of Japanese literature?",
    answers_ja: ["清少納言", "紫式部", "和泉式部", "小野小町"],
    answers_en: [
      "Sei Shonagon",
      "Murasaki Shikibu",
      "Izumi Shikibu",
      "Ono no Komachi",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「叫び」で有名な画家は誰か？",
    question_en: "Who is the painter famous for 'The Scream'?",
    answers_ja: ["ゴッホ", "ムンク", "ピカソ", "ダリ"],
    answers_en: ["Van Gogh", "Munch", "Picasso", "Dalí"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "芥川龍之介の代表作はどれか？",
    question_en:
      "Which is a representative work by Ryunosuke Akutagawa, one of Japan's most renowned modern authors?",
    answers_ja: ["坊っちゃん", "雪国", "羅生門", "人間失格"],
    answers_en: ["Botchan", "Snow Country", "Rashomon", "No Longer Human"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "『老人と海』の作者は誰か？",
    question_en: "Who is the author of 'The Old Man and the Sea'?",
    answers_ja: [
      "マーク・トウェイン",
      "フィッツジェラルド",
      "スタインベック",
      "ヘミングウェイ",
    ],
    answers_en: [
      "Mark Twain",
      "F. Scott Fitzgerald",
      "John Steinbeck",
      "Ernest Hemingway",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「印象・日の出」を描いた画家は誰か？",
    question_en: "Who painted 'Impression, Sunrise'?",
    answers_ja: ["モネ", "ルノワール", "セザンヌ", "マネ"],
    answers_en: ["Monet", "Renoir", "Cézanne", "Manet"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "『罪と罰』の作者は誰か？",
    question_en: "Who is the author of 'Crime and Punishment'?",
    answers_ja: ["トルストイ", "ドストエフスキー", "チェーホフ", "ゴーゴリ"],
    answers_en: ["Tolstoy", "Dostoevsky", "Chekhov", "Gogol"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "夏目漱石の作品でないものはどれか？",
    question_en:
      "Which of the following is NOT a work by Natsume Soseki, a leading figure in modern Japanese literature?",
    answers_ja: ["坊っちゃん", "吾輩は猫である", "舞姫", "こころ"],
    answers_en: ["Botchan", "I Am a Cat", "The Dancing Girl", "Kokoro"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「ゲルニカ」を描いた画家は誰か？",
    question_en: "Who painted 'Guernica'?",
    answers_ja: ["ダリ", "ミロ", "マティス", "ピカソ"],
    answers_en: ["Dalí", "Miró", "Matisse", "Picasso"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "『万葉集』に最も多くの歌を残した歌人は誰か？",
    question_en:
      "Who contributed the most poems to the 'Man'yoshu', Japan's oldest anthology of poetry?",
    answers_ja: ["大伴家持", "柿本人麻呂", "山上憶良", "額田王"],
    answers_en: [
      "Otomo no Yakamochi",
      "Kakinomoto no Hitomaro",
      "Yamanoue no Okura",
      "Princess Nukata",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ノーベル文学賞を受賞した日本人作家はどれか？",
    question_en: "Which Japanese author won the Nobel Prize in Literature?",
    answers_ja: ["三島由紀夫", "川端康成", "太宰治", "芥川龍之介"],
    answers_en: [
      "Yukio Mishima",
      "Yasunari Kawabata",
      "Osamu Dazai",
      "Ryunosuke Akutagawa",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "『ハムレット』を書いた劇作家は誰か？",
    question_en: "Who wrote the play 'Hamlet'?",
    answers_ja: ["モリエール", "ゲーテ", "シェイクスピア", "チェーホフ"],
    answers_en: ["Molière", "Goethe", "Shakespeare", "Chekhov"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 政治・経済・法律の基礎 =====
  {
    question_ja: "日本の衆議院議員の任期は何年か？",
    question_en:
      "What is the term of office for members of Japan's House of Representatives?",
    answers_ja: ["3年", "5年", "6年", "4年"],
    answers_en: ["3 years", "5 years", "6 years", "4 years"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本銀行の主な役割として正しいのはどれか？",
    question_en: "What is the primary role of the Bank of Japan?",
    answers_ja: [
      "通貨の発行と金融政策の実施",
      "国防の管理",
      "外交交渉",
      "法律の制定",
    ],
    answers_en: [
      "Issuing currency and implementing monetary policy",
      "Managing national defense",
      "Diplomatic negotiations",
      "Enacting laws",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "GDPとは何の略称か？",
    question_en: "What does GDP stand for?",
    answers_ja: [
      "General Domestic Production",
      "Gross Domestic Product",
      "Global Development Program",
      "Government Debt Policy",
    ],
    answers_en: [
      "General Domestic Production",
      "Gross Domestic Product",
      "Global Development Program",
      "Government Debt Policy",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "三権分立の「三権」に含まれないものはどれか？",
    question_en:
      "Which of the following is NOT one of the three branches of government in the separation of powers?",
    answers_ja: ["立法権", "司法権", "報道権", "行政権"],
    answers_en: [
      "Legislative power",
      "Judicial power",
      "Press power",
      "Executive power",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の参議院議員の任期は何年か？",
    question_en:
      "What is the term of office for members of Japan's House of Councillors?",
    answers_ja: ["3年", "4年", "5年", "6年"],
    answers_en: ["3 years", "4 years", "5 years", "6 years"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "インフレーションとはどのような現象か？",
    question_en: "What is inflation?",
    answers_ja: [
      "物価が持続的に上昇すること",
      "物価が持続的に下落すること",
      "為替レートが変動すること",
      "失業率が上昇すること",
    ],
    answers_en: [
      "A sustained increase in the general price level",
      "A sustained decrease in the general price level",
      "Fluctuation of exchange rates",
      "An increase in the unemployment rate",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の最高裁判所の裁判官の人数は何人か？",
    question_en: "How many justices serve on Japan's Supreme Court?",
    answers_ja: ["9人", "15人", "11人", "21人"],
    answers_en: ["9", "15", "11", "21"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja:
      "日本国憲法で保障される「国民の三大義務」に含まれないのはどれか？",
    question_en:
      "Which is NOT one of the three major duties of citizens guaranteed by the Constitution of Japan?",
    answers_ja: [
      "勤労の義務",
      "納税の義務",
      "投票の義務",
      "教育を受けさせる義務",
    ],
    answers_en: [
      "Duty to work",
      "Duty to pay taxes",
      "Duty to vote",
      "Duty to ensure children receive education",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja:
      "需要と供給の法則で、需要が増加すると一般的に価格はどうなるか？",
    question_en:
      "According to the law of supply and demand, what generally happens to prices when demand increases?",
    answers_ja: ["変わらない", "下がる", "不安定になる", "上がる"],
    answers_en: ["Stay the same", "Decrease", "Become unstable", "Increase"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の選挙権年齢は何歳以上か？",
    question_en: "What is the minimum voting age in Japan?",
    answers_ja: ["18歳以上", "20歳以上", "16歳以上", "25歳以上"],
    answers_en: [
      "18 and older",
      "20 and older",
      "16 and older",
      "25 and older",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の内閣総理大臣を指名するのはどの機関か？",
    question_en: "Which body designates the Prime Minister of Japan?",
    answers_ja: ["天皇", "国会", "最高裁判所", "内閣"],
    answers_en: [
      "The Emperor",
      "The National Diet",
      "The Supreme Court",
      "The Cabinet",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "累進課税制度の特徴はどれか？",
    question_en: "What is the characteristic of a progressive tax system?",
    answers_ja: [
      "全員同じ税率",
      "所得が低いほど税率が高い",
      "所得が高いほど税率が高い",
      "税金がかからない",
    ],
    answers_en: [
      "Everyone pays the same tax rate",
      "Lower income means a higher tax rate",
      "Higher income means a higher tax rate",
      "No taxes are levied",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 生物・医学 =====
  {
    question_ja: "ヒトの体内で最も大きな臓器はどれか？",
    question_en: "What is the largest organ in the human body?",
    answers_ja: ["脳", "心臓", "肺", "肝臓"],
    answers_en: ["Brain", "Heart", "Lungs", "Liver"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "光合成を行う細胞内の構造体はどれか？",
    question_en: "Which cellular organelle carries out photosynthesis?",
    answers_ja: ["葉緑体", "ミトコンドリア", "リボソーム", "ゴルジ体"],
    answers_en: ["Chloroplast", "Mitochondria", "Ribosome", "Golgi apparatus"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ヒトの血液型で、ABO式の型を決定するのは何か？",
    question_en: "What determines the ABO blood type in humans?",
    answers_ja: ["白血球", "赤血球の表面抗原", "血小板", "血漿タンパク質"],
    answers_en: [
      "White blood cells",
      "Surface antigens on red blood cells",
      "Platelets",
      "Plasma proteins",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ヒトの染色体の数は何本か？",
    question_en: "How many chromosomes do humans have?",
    answers_ja: ["23本", "44本", "46本", "48本"],
    answers_en: ["23", "44", "46", "48"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "インスリンを分泌する臓器はどれか？",
    question_en: "Which organ secretes insulin?",
    answers_ja: ["肝臓", "腎臓", "甲状腺", "膵臓"],
    answers_en: ["Liver", "Kidney", "Thyroid gland", "Pancreas"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "細胞のエネルギー通貨と呼ばれる物質はどれか？",
    question_en: "Which molecule is known as the energy currency of the cell?",
    answers_ja: ["ATP", "DNA", "RNA", "タンパク質"],
    answers_en: ["ATP", "DNA", "RNA", "Protein"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ヒトの小腸の主な役割はどれか？",
    question_en: "What is the main function of the human small intestine?",
    answers_ja: ["食物の貯蔵", "栄養素の吸収", "水分の吸収", "食物の粉砕"],
    answers_en: [
      "Storing food",
      "Absorbing nutrients",
      "Absorbing water",
      "Grinding food",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "遺伝情報の伝達で、DNAからmRNAを作る過程を何というか？",
    question_en: "What is the process of creating mRNA from DNA called?",
    answers_ja: ["翻訳", "複製", "転写", "変異"],
    answers_en: ["Translation", "Replication", "Transcription", "Mutation"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "抗体を産生する細胞はどれか？",
    question_en: "Which cells produce antibodies?",
    answers_ja: ["赤血球", "血小板", "マクロファージ", "B細胞（形質細胞）"],
    answers_en: [
      "Red blood cells",
      "Platelets",
      "Macrophages",
      "B cells (plasma cells)",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "メンデルの法則で、対立遺伝子が分離する法則を何というか？",
    question_en:
      "In Mendel's laws, what is the law that states alleles separate during gamete formation?",
    answers_ja: ["分離の法則", "独立の法則", "優性の法則", "連鎖の法則"],
    answers_en: [
      "Law of Segregation",
      "Law of Independent Assortment",
      "Law of Dominance",
      "Law of Linkage",
    ],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ヒトの体温調節の中枢はどこにあるか？",
    question_en:
      "Where is the center for body temperature regulation located in the human body?",
    answers_ja: ["大脳", "視床下部", "小脳", "延髄"],
    answers_en: ["Cerebrum", "Hypothalamus", "Cerebellum", "Medulla oblongata"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "植物の気孔の主な役割はどれか？",
    question_en: "What is the main function of stomata in plants?",
    answers_ja: ["光の吸収", "水の吸収", "ガス交換と蒸散", "養分の貯蔵"],
    answers_en: [
      "Absorbing light",
      "Absorbing water",
      "Gas exchange and transpiration",
      "Storing nutrients",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  // ===== 数学 =====
  {
    question_ja: "円周率πの値に最も近いのはどれか？",
    question_en: "Which value is closest to pi (π)?",
    answers_ja: ["2.718", "3.000", "3.333", "3.141"],
    answers_en: ["2.718", "3.000", "3.333", "3.141"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "1から100までの自然数の合計はいくつか？",
    question_en: "What is the sum of all natural numbers from 1 to 100?",
    answers_ja: ["5050", "4950", "5500", "5100"],
    answers_en: ["5,050", "4,950", "5,500", "5,100"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "2の10乗はいくつか？",
    question_en: "What is 2 to the power of 10?",
    answers_ja: ["512", "1024", "2048", "256"],
    answers_en: ["512", "1,024", "2,048", "256"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "直角三角形の斜辺の長さを求める定理はどれか？",
    question_en:
      "Which theorem is used to find the length of the hypotenuse of a right triangle?",
    answers_ja: [
      "フェルマーの定理",
      "中間値の定理",
      "三平方の定理",
      "余弦定理",
    ],
    answers_en: [
      "Fermat's theorem",
      "Intermediate value theorem",
      "Pythagorean theorem",
      "Law of cosines",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "素数でないものはどれか？",
    question_en: "Which of the following is NOT a prime number?",
    answers_ja: ["2", "17", "23", "27"],
    answers_en: ["2", "17", "23", "27"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "log₁₀(1000)の値はいくつか？",
    question_en: "What is the value of log₁₀(1000)?",
    answers_ja: ["3", "10", "100", "30"],
    answers_en: ["3", "10", "100", "30"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "正六角形の内角の和は何度か？",
    question_en: "What is the sum of the interior angles of a regular hexagon?",
    answers_ja: ["360度", "720度", "540度", "900度"],
    answers_en: ["360 degrees", "720 degrees", "540 degrees", "900 degrees"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "虚数単位iの定義として正しいのはどれか？",
    question_en: "Which is the correct definition of the imaginary unit i?",
    answers_ja: ["i = -1", "i = 0", "i² = -1", "i² = 1"],
    answers_en: ["i = -1", "i = 0", "i² = -1", "i² = 1"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "フィボナッチ数列の最初の7項（1,1,2,3,5,8,?）の?に入る数は？",
    question_en:
      "What is the 7th term in the Fibonacci sequence (1, 1, 2, 3, 5, 8, ?)?",
    answers_ja: ["10", "11", "12", "13"],
    answers_en: ["10", "11", "12", "13"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "球の体積を求める公式はどれか？",
    question_en: "Which formula calculates the volume of a sphere?",
    answers_ja: ["(4/3)πr³", "4πr²", "πr²h", "2πr"],
    answers_en: ["(4/3)πr³", "4πr²", "πr²h", "2πr"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "階乗「5!」の値はいくつか？",
    question_en: "What is the value of 5! (5 factorial)?",
    answers_ja: ["60", "120", "24", "720"],
    answers_en: ["60", "120", "24", "720"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "sin 30°の値はいくつか？",
    question_en: "What is the value of sin 30°?",
    answers_ja: ["1", "√3/2", "1/2", "√2/2"],
    answers_en: ["1", "√3/2", "1/2", "√2/2"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "自然対数の底eの値に最も近いのはどれか？",
    question_en: "Which value is closest to Euler's number e?",
    answers_ja: ["1.414", "2.236", "3.141", "2.718"],
    answers_en: ["1.414", "2.236", "3.141", "2.718"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  // ===== 音楽・映画・文化 =====
  {
    question_ja: "「運命」（交響曲第5番）を作曲したのは誰か？",
    question_en: "Who composed Symphony No. 5, commonly known as 'Fate'?",
    answers_ja: ["ベートーヴェン", "モーツァルト", "バッハ", "ショパン"],
    answers_en: ["Beethoven", "Mozart", "Bach", "Chopin"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "映画『ローマの休日』の主演女優は誰か？",
    question_en: "Who was the lead actress in the film 'Roman Holiday'?",
    answers_ja: [
      "マリリン・モンロー",
      "オードリー・ヘプバーン",
      "エリザベス・テイラー",
      "グレース・ケリー",
    ],
    answers_en: [
      "Marilyn Monroe",
      "Audrey Hepburn",
      "Elizabeth Taylor",
      "Grace Kelly",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の伝統芸能「歌舞伎」の創始者とされるのは誰か？",
    question_en:
      "Who is considered the founder of Kabuki, a traditional Japanese performing art?",
    answers_ja: ["世阿弥", "近松門左衛門", "出雲阿国", "観阿弥"],
    answers_en: ["Zeami", "Chikamatsu Monzaemon", "Izumo no Okuni", "Kan'ami"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja:
      "映画『スター・ウォーズ』シリーズの監督（オリジナル三部作）は誰か？",
    question_en: "Who directed the original Star Wars trilogy?",
    answers_ja: [
      "スティーブン・スピルバーグ",
      "ジェームズ・キャメロン",
      "リドリー・スコット",
      "ジョージ・ルーカス",
    ],
    answers_en: [
      "Steven Spielberg",
      "James Cameron",
      "Ridley Scott",
      "George Lucas",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ピアノの鍵盤は全部で何鍵あるか（標準的なグランドピアノ）？",
    question_en: "How many keys does a standard grand piano have?",
    answers_ja: ["88鍵", "76鍵", "92鍵", "84鍵"],
    answers_en: ["88 keys", "76 keys", "92 keys", "84 keys"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「四季」を作曲したイタリアの作曲家は誰か？",
    question_en: "Who is the Italian composer of 'The Four Seasons'?",
    answers_ja: ["パガニーニ", "ヴィヴァルディ", "ヴェルディ", "プッチーニ"],
    answers_en: ["Paganini", "Vivaldi", "Verdi", "Puccini"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の国技とされる相撲で、最高位の力士の称号は何か？",
    question_en:
      "In sumo wrestling, Japan's national sport, what is the highest rank a wrestler can achieve?",
    answers_ja: ["大関", "関脇", "横綱", "小結"],
    answers_en: ["Ozeki", "Sekiwake", "Yokozuna", "Komusubi"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "アカデミー賞の通称は何か？",
    question_en: "What is the Academy Awards commonly known as?",
    answers_ja: ["グラミー賞", "エミー賞", "トニー賞", "オスカー"],
    answers_en: ["Grammy Awards", "Emmy Awards", "Tony Awards", "The Oscars"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「ボヘミアン・ラプソディ」を歌ったバンドはどれか？",
    question_en: "Which band performed 'Bohemian Rhapsody'?",
    answers_ja: [
      "クイーン",
      "ビートルズ",
      "レッド・ツェッペリン",
      "ローリング・ストーンズ",
    ],
    answers_en: ["Queen", "The Beatles", "Led Zeppelin", "The Rolling Stones"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "茶道の三千家に含まれないのはどれか？",
    question_en:
      "Which is NOT one of the three main schools (San-Senke) of the Japanese tea ceremony?",
    answers_ja: ["表千家", "裏千家", "遠州流", "武者小路千家"],
    answers_en: ["Omotesenke", "Urasenke", "Enshu-ryu", "Mushakojisenke"],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "映画『千と千尋の神隠し』の監督は誰か？",
    question_en: "Who directed the animated film 'Spirited Away'?",
    answers_ja: ["細田守", "宮崎駿", "新海誠", "高畑勲"],
    answers_en: [
      "Mamoru Hosoda",
      "Hayao Miyazaki",
      "Makoto Shinkai",
      "Isao Takahata",
    ],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "音楽用語で「フォルテ（forte）」はどのような意味か？",
    question_en: "What does the musical term 'forte' mean?",
    answers_ja: ["遅く", "速く", "弱く", "強く"],
    answers_en: ["Slowly", "Quickly", "Softly", "Loudly"],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
  {
    question_ja: "太陽系で最も大きい惑星はどれか？",
    question_en: "Which is the largest planet in the solar system?",
    answers_ja: ["木星", "土星", "天王星", "海王星"],
    answers_en: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctIndex: 0,
    difficulty: "medium" as const,
  },
  {
    question_ja: "ノーベル賞の授賞式が行われる都市はどこか？（平和賞を除く）",
    question_en:
      "In which city is the Nobel Prize ceremony held (excluding the Peace Prize)?",
    answers_ja: [
      "ジュネーブ",
      "ストックホルム",
      "コペンハーゲン",
      "ヘルシンキ",
    ],
    answers_en: ["Geneva", "Stockholm", "Copenhagen", "Helsinki"],
    correctIndex: 1,
    difficulty: "medium" as const,
  },
  {
    question_ja: "日本の都道府県で最も面積が大きいのはどこか？",
    question_en: "Which is the largest prefecture in Japan by area?",
    answers_ja: ["岩手県", "長野県", "北海道", "新潟県"],
    answers_en: [
      "Iwate Prefecture",
      "Nagano Prefecture",
      "Hokkaido",
      "Niigata Prefecture",
    ],
    correctIndex: 2,
    difficulty: "medium" as const,
  },
  {
    question_ja: "「白鳥の湖」を作曲したのは誰か？",
    question_en: "Who composed 'Swan Lake'?",
    answers_ja: [
      "ストラヴィンスキー",
      "ラフマニノフ",
      "リムスキー＝コルサコフ",
      "チャイコフスキー",
    ],
    answers_en: [
      "Stravinsky",
      "Rachmaninoff",
      "Rimsky-Korsakov",
      "Tchaikovsky",
    ],
    correctIndex: 3,
    difficulty: "medium" as const,
  },
];
